trigger: none
pr: none

stages:
- stage: Delete_Docker_Images
  displayName: Delete Docker Images
  jobs:
    - job: DockerCleanBuildAndTest
      displayName: Docker Build and Test
      workspace:
        clean: all
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'docker rmi nginx'